### ISSUE TITLE
Hello, about binding hotkey brightness

### ISSUE THREAD

**Issue by hubgogo** [bkader/Dominos#2]
- I am very happy to use your plugin, there is a problem that has been bothering me

Dominos cannot highlight bound keys like ElvUI and Bartender4

The picture below shows the binding hotkey of ElvUI
![搜狗截图20211001043353](https://user-images.githubusercontent.com/91697479/135527500-f2f72820-0750-48f5-9878-4954a5cb3dfa.png)

That's ok

- Key bindings for Dominos
![搜狗截图20211001043813](https://user-images.githubusercontent.com/91697479/135527689-031962ad-e197-497c-9511-35d783291ad1.png)

The superposition of pets and items is normal highlighting

The hotkey bound to the action bar is gray

It's not ok

- Could you please help me adjust it?

Thanks a lot

**Comment by bkader** [comment]
Hello @hubgogo .. What addon are you using to Skin your Dominos buttons? It can be the reason behind this and not Dominos itself.

**Comment by hubgogo** [comment]
Hello bkader
Glad your reply
Dominos skin button addons
bkader/ButtonFacade
[https://github.com/bkader/ButtonFacade#buttonfacade-with-28-skins](url)

skin ：Dream Layout



https://user-images.githubusercontent.com/91697479/135705571-52493f67-946d-4384-9210-2addedb09473.mp4


thanks

**Comment by bkader** [comment]
Check [this link](https://www.townlong-yak.com/framexml/3.3.5/ActionButtonTemplate.xml#13) you will understand why it's gray. It has nothing to do with **Dominos** or **ButtonFacade**. You might want to edit the Skin you're using to make it white.

**Comment by hubgogo** [comment]
Thank you, I won't be able to adjust, so I gave up.
