### ISSUE TITLE
Weapon Enchantment is missing from the Buffs & Debuffs module.

### ISSUE THREAD

**Issue by azorim123** [bkader/Dominos#4]
Hello, I'm using the Dominos addon and I noticed that the weapon enchantments are not in the buffs & debuffs module (rogue, shaman, warlock), I would appreciate if there is any way to fix this problem. thank you
![image](https://user-images.githubusercontent.com/67609281/169670314-88b29393-b813-457a-a519-5bc9c48d9d7b.png)
![image](https://user-images.githubusercontent.com/67609281/169670320-b0590fe0-49b4-4de3-9e2c-45c6b58f85fc.png)

**Comment by bkader** [comment]
@azorim123 this was not a problem, it was not meant for _Temporary Enchants_ but if I can find an easy way to include them I will, otherwise ...
